### ISSUE TITLE
How to use GeoPathContext

### ISSUE THREAD

**Issue by jimmyff** [luizbarboza/d4_geo#1]
Hey, thanks for these packages -really awesome work! 🙌 

I'm just playing around and I've managed to get the SVG topojson & projections working but I'm unsure how to utilise the `GeoPathContext` to create a canvas renderer. I've tried to create a flutter CustomPainter but I'm not having any luck and think I'm approaching it incorrectly. I've looked through the tests so understand what it's doing, but just unsure how I should implement. Any advice would be great.

Thanks again

**Comment by luizbarboza** [comment]
The `GeoPathContext` class is an implementation of the `GeoStream` class that effectively translates `GeoStream` method calls into a subset of `CanvasRenderingContext2D` API calls.

To use this class, you have two options:
- Implement these methods on top of the `dart:ui` `Path` and pass them via the constructor, or
- Directly pass the methods of the `dart:html` `CanvasRenderingContext2D`.

The downside of the second option is that it only works for web applications. The first option might seem a bit complicated, which is why I'm already developing a library on top of the `d4` package to facilitate various drawings using the Flutter SDK.

**Comment by jimmyff** [comment]
Hey thanks for the feedback, yes it was the first option I was going for.  The issue I'm having is the Flutter canvas api is so different from the html canvas api. This is the kind of thing I've got so far (not working code)

```dart
class D3Painter extends CustomPainter {
  final d4geo.GeoProjection projection;
  final Map<String?, dynamic> land;
  final Map<dynamic, dynamic> graticule;

  const D3Painter({
    required this.projection,
    required this.land,
    required this.graticule,
  });

  @override
  void paint(Canvas canvas, Size size) {
    // Geo Path
    var path = d4.GeoPath(
        d4geo.geoNaturalEarth1(),
        d4.GeoPathContext((x, y) {
          path.moveTo(x as double, y as double);
        }, (x, y) {
          path.lineTo(x as double, y as double);
        }, (x, y, radius, startAngle, endAngle) {
          canvas.drawArc(
              Rect.fromCircle(
                center: Offset(x as double, y as double),
                radius: radius as double,
              ),
              startAngle as double,
              endAngle as double,
              false,
              Paint());
        }, () {
          path.close();
        }));

    // Draw land
    canvas.drawPath(path(land), Paint()..color = Colors.green);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;
}
```

I'm struggling to wrap my head around how I can make this work with the current `GeoPathContext` -I'm sure I'm missing something really obvious?

The library you're building on top sounds really interesting, is there anything in the public I could gander at? might help me figure out where I'm going wrong! 

Thanks

**Comment by luizbarboza** [comment]
The `GeoPath` class instance is called to draw the land on the underlying path. The land is then drawn on the path, and the path needs to be drawn on the canvas.

```dart
import 'dart:math';

import 'package:d4/d4.dart' as d4;
import 'package:flutter/material.dart';

class GeoPainter extends CustomPainter {
  final d4.GeoProjection projection;
  final Map<String?, dynamic> land;
  final Map<dynamic, dynamic> graticule;

  const GeoPainter({
    required this.projection,
    required this.land,
    required this.graticule,
  });

  @override
  void paint(Canvas canvas, Size size) {
    // Underlying Path
    var path = Path();

    // Geo Path
    var geoPath = d4.GeoPath(
      d4.geoNaturalEarth1(),
      d4.GeoPathContext(
        (x, y) {
          path.moveTo(x as double, y as double);
        },
        (x, y) {
          path.lineTo(x as double, y as double);
        },
        (x, y, radius, startAngle, endAngle) {
          path.addArc(
            Rect.fromCircle(
              center: Offset(x.toDouble(), y.toDouble()),
              radius: radius.toDouble(),
            ),
            0,
            pi * 2,
          );
        },
        () {
          path.close();
        },
      ),
    );

    // Draw the land on the underlying path
    geoPath(land);

    // Draw the underlying path on the canvas
    canvas.drawPath(path, Paint()..color = Colors.green);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;
}
```

**Comment by jimmyff** [comment]
Ah thank you for that -I wasn't actually too far off! 😅 

That's really helpful. Thanks again for the great work on these packages.
